-- DROP AND CREATE DB.
DROP DATABASE IF EXIST kaptiva_rental;
CREATE DATABASE kaptiva_rental;

-- SELECT DB TO WORK.
USE DATABASE kaptiva_rental;

CREATE TABLE rental (
  rental_order INT(10) AUTO_INCREMENT NOT NULL PRIMARY KEY, -- THIS WILL HOLD A CODE OF RENTAL
  value INT(10) NOT NULL, -- SAVES DE AMOUNT OF MONEY FOM THE ORDER
  date CURRENT_DATE,
  time CURRENT_TIME,
  due_date 
  client INT,
  FOREGIN KEY (client) FOREGIN KEY REFERENCES Clients(id);
)
